### ISSUE TITLE
运行应用奔溃

### ISSUE THREAD

**Issue by lshAndroid** [qidashi/EthernetDemo#1]
直接使用项目在Android 5.1系统控制直接奔溃。甚至放到虚拟机上也控制奔溃 
错误信息： java.lang.NoSuchMethodError: No virtual method getEthernetIfaceState()I in class Landroid/net/EthernetManager; or its super classes (declaration of 'android.net.EthernetManager' appears in /system/framework/framework.jar)

**Comment by gxs-gc** [comment]
me too 你解决了吗

**Comment by diyhlgc** [comment]
作者能回复一下吗？

**Comment by gxbcom** [comment]
java.lang.NoSuchMethodError: No virtual method setEthernetEnabled(Z)Z in class Landroid/net/EthernetManager; or its super classes (declaration of 'android.net.EthernetManager' appears in /system/framework/framework.jar)
        at com.mayday.ethernetdemo.EthernetMain.closeEth(EthernetMain.java:57)
        at com.mayday.ethernetdemo.MainActivity.onClick(MainActivity.java:61)

**Comment by caesura-k** [comment]
同奔溃来着

**Comment by youngbais** [comment]
安卓10也一样闪退.

**Comment by diyhlgc** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
